language: node_js
node_js:
- node
before_deploy:
- npm run build
deploy:
  provider: npm
  email: anthony.kerz@gmail.com
  api_key:
    secure: zzS0/TgOqiF+OM5xAe1NT2m7IU+TbS1brdSWP+FbEXtZHWnvNrs6KcnjWk0vhgoR6jJaq95PaeADVsIvF0tY+q8/+WlTFYzT8DO084vekHzox2apbYKBpTNyIbRhc0GI1mpr+JeOvSLb0+nYjgxhvqlVF/Bv1qjdmdqIfzJCgPEuTfWOhisMrOmZ1wvoSQhRjggRKD9Z1w7plYe6hONhkz+MARxS8doxsqgWPWbTRSZzWRj3FhsHVhX7VqLd7QP+biTHElhiqKgJuCDvyLm0IabO/1wpvP3TkKhhSzOsqyGsrl4h7Z+9/094OyhdevzGmGupStLKFXSpwe6iEUYrCUcFJLBb2UINj+dLoL648p4+yvVeElkyrA9IDVkpRQOg9S1n+wXDWJtv8ncPi8xcYBf7UgeKc1qHbZjBCnvMyjpKEIeT67C1iyirfXgXfdSQXIVk9tTOX4ycpRJ6KHHD5f/No+fm0fYASVCnDHfisOthHTIu5uAsXlhgkHio1vlM+CfMRbOFV7Pur3SH7BqYJ3gWmWc9Gr7v4iw2tcoaucHDDHTOS5mhp/XcRhaszYDNDrZuVYslQm9nV4/hIcTT7jMov0m1RWYDbUvS45ec8KMdqx6zmMzV6TCnYTDFtq9ZHTb9pW+TlGec9/JCo0/kVxqcutlNqXjfBiAxNx7m0jM=
  skip_cleanup: true
  on:
    branch: master
    condition: "-z $TRAVIS_TAG"
