language: node_js
node_js:
- node
before_deploy:
- npm run build
deploy:
  provider: npm
  email: anthony.kerz@gmail.com
  api_key:
    secure: GRRUnzZIHQkqv6K2MvAP5eT+DAwZHMBPVX678DE8G9sZx3Kg2aJqDKjGwGdpCaX5/k6ipb2v0eZFaFEa3DAbKw+JkO4ym2Sd/wG/Rt0TGCw3lIvwf5UDGSM8m1irAVRWwIRK6GdpIC/A/PF2zpqvudeq7nYhdHE/poJX2B/B1G3l/rAIKY+DnYjMyp4n9Jo6NRHTZwrJa2e7QUWVJw53oIOCvMQD/ebRlb4j+9s4mYjbYbJJi1nDklOEsgmd4mpfsi/fUxnU3ktPu400EZsbkyF6QawFiRpnQ4JVkUa7ZfzT565XgpjyCnnZNs0ooVVMnZoyFnRaDX8aumoKhgBUHwGFDbCZFNQUase862V2eDoObbl1PnXe58L50vY4H6KEebaXadIrcCNAT5gfl02j4qIUn5UKoReAas42n74BTtALE7wNpjf9yJCBkDcHG/8mIqvQzVjHavO9NAsn09nZIjfSJaUTh8erlwicAI8hM9NlRVqrMTeqJRdjahVt0a+2gJnvnNy/OEomaBAFeSP9ePIAyaEp35bEERULAB9qZU2tkIS+P02E/ZryUfMNixua00srP5yw/6sRF3bPDC0hECQBa2Ts/J45UGJM0tu40GMITJ4I6XjCZFme4e8XXqD13kFgKmywMo1gdsB2au76XnLOryqMDL2DKKZfbj2PNvI=
  skip_cleanup: true
  on:
    branch: master
    condition: "-z $TRAVIS_TAG"
