language: node_js
node_js:
- node
before_deploy:
- npm run build
deploy:
  provider: npm
  email: anthony.kerz@gmail.com
  api_key:
    secure: hfyyF4iPVZQ4gZ6IFEhNynOp2RvEfdKKvrLfs3A2YRXtIL1/NQ9uoMYpr9mYANHIR635BImYi3aeq9kjjNty++UB0P5AUGxnP3xvEciqYDL2bdk/Q2G+0b7Lp7xDUjqySvNxx8hYc6JOuxgH4uX4+stU3YOZ/h7PNqfNSRJKVxZZdXhkFBj0qVpXwV6r9K2pyJn5DggkLxsu92kZciYLi7aRq24CNXt9Dd81hw2Pi1hHaOkZRfd4rXtj1EOoYfjy+gQ/Xsve31jQ4wWvJsfO12TIVnc6Co9h0jTAAXfkL8zFsCB5MczGol/Q2eMY65MGB4s836I4fo6rvscxl+QUTVxTNtskm2jwMvhVieM3bbyMJVZBQ4AKXUGVFLnOL5kbkfzY2Cu0FL2RR3UzBNwKZzrGcSBWauI7iOoMvDpmdLoQ1l9Iw47GMiW3zEb/F4nKqYadAnR3zX2cjJSo4tOefVegg007oGyuz8eSeVw1/z81MXUNNEb+UysGqOgjbrAzXwcVXnohLmYPhLvyRWvCVJZ9kVVEUCeWPUSOfY503v8CWo1MFqMaZUgmTsGMGHccXAm49mmaPaS9/1AztBbYtRzuqeMjV/rU7R1ESki4dnxVvXJK7VXfQHQAAap8tRuYkvdan0lZbvtg8sU8oxscQNAEt4+zczuH5XgTgi1rgK0=
  skip_cleanup: true
  on:
    branch: master
    condition: "-z $TRAVIS_TAG"
